from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.models.user import User, UserProfile
from app.schemas.user import UserCreate, UserUpdate


class UserService:
    async def get_by_id(self, db: AsyncSession, user_id: UUID) -> User | None:
        """Get a user by ID, including their profile."""
        query = (
            select(User).options(selectinload(User.profile)).where(User.id == user_id)
        )
        result = await db.execute(query)
        return result.scalars().first()

    async def get_by_whatsapp_number(
        self, db: AsyncSession, whatsapp_number: str
    ) -> User | None:
        """Get a user by their WhatsApp number, including profile."""
        query = (
            select(User)
            .join(UserProfile)
            .options(selectinload(User.profile))
            .where(UserProfile.whatsapp_number == whatsapp_number)
        )
        result = await db.execute(query)
        return result.scalars().first()

    async def create(self, db: AsyncSession, user_in: UserCreate) -> User:
        """Create a new user with their profile."""
        new_user = User()
        db.add(new_user)
        # Flush to get the new_user.id generated by DB
        await db.flush()

        profile_data = user_in.profile.model_dump()
        new_profile = UserProfile(user_id=new_user.id, **profile_data)
        db.add(new_profile)

        await db.commit()
        await db.refresh(new_user)
        # Reload to eagerly load profile
        return await self.get_by_id(db, new_user.id)

    async def update(
        self, db: AsyncSession, *, db_obj: User, obj_in: UserUpdate | dict
    ) -> User:
        """Update a user and/or their profile."""
        if isinstance(obj_in, dict):
            update_data = obj_in
        else:
            update_data = obj_in.model_dump(exclude_unset=True)

        if "is_active" in update_data:
            db_obj.is_active = update_data["is_active"]

        if "profile" in update_data and db_obj.profile:
            profile_data = update_data["profile"]
            for field, value in profile_data.items():
                setattr(db_obj.profile, field, value)

        db.add(db_obj)
        await db.commit()
        await db.refresh(db_obj)
        return await self.get_by_id(db, db_obj.id)


user_service = UserService()
