"""add_terms_accepted_at_to_users

Revision ID: 075fe2120f39
Revises: 095d598bceb9
Create Date: 2026-04-02 19:35:01.190157

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "075fe2120f39"
down_revision: str | Sequence[str] | None = "095d598bceb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("terms_accepted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "terms_accepted_at")
    # ### end Alembic commands ###
