"""add_ondelete_cascade_to_all_user_fks

Revision ID: 1657b31fc815
Revises: 075fe2120f39
Create Date: 2026-04-24 17:03:46.087930

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1657b31fc815"
down_revision: str | Sequence[str] | None = "075fe2120f39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("adherence_reports_user_id_fkey"), "adherence_reports", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "adherence_reports", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("medications_user_id_fkey"), "medications", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "medications", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("fk_message_logs_reminder_log_id"), "message_logs", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("message_logs_user_id_fkey"), "message_logs", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "message_logs", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "message_logs",
        "reminder_logs",
        ["reminder_log_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("payments_subscription_id_fkey"), "payments", type_="foreignkey"
    )
    op.drop_constraint(op.f("payments_user_id_fkey"), "payments", type_="foreignkey")
    op.create_foreign_key(
        None, "payments", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "payments",
        "subscriptions",
        ["subscription_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("reminder_logs_user_id_fkey"), "reminder_logs", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("reminder_logs_schedule_id_fkey"), "reminder_logs", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "reminder_logs", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "reminder_logs",
        "medication_schedules",
        ["schedule_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("subscriptions_user_id_fkey"), "subscriptions", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "subscriptions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subscriptions", type_="foreignkey")
    op.create_foreign_key(
        op.f("subscriptions_user_id_fkey"),
        "subscriptions",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "reminder_logs", type_="foreignkey")
    op.drop_constraint(None, "reminder_logs", type_="foreignkey")
    op.create_foreign_key(
        op.f("reminder_logs_schedule_id_fkey"),
        "reminder_logs",
        "medication_schedules",
        ["schedule_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("reminder_logs_user_id_fkey"),
        "reminder_logs",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.create_foreign_key(
        op.f("payments_user_id_fkey"), "payments", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("payments_subscription_id_fkey"),
        "payments",
        "subscriptions",
        ["subscription_id"],
        ["id"],
    )
    op.drop_constraint(None, "message_logs", type_="foreignkey")
    op.drop_constraint(None, "message_logs", type_="foreignkey")
    op.create_foreign_key(
        op.f("message_logs_user_id_fkey"), "message_logs", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_message_logs_reminder_log_id"),
        "message_logs",
        "reminder_logs",
        ["reminder_log_id"],
        ["id"],
    )
    op.drop_constraint(None, "medications", type_="foreignkey")
    op.create_foreign_key(
        op.f("medications_user_id_fkey"), "medications", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "adherence_reports", type_="foreignkey")
    op.create_foreign_key(
        op.f("adherence_reports_user_id_fkey"),
        "adherence_reports",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
