"""add_ondelete_cascade_to_all_user_fks

Revision ID: 1657b31fc815
Revises: 075fe2120f39
Create Date: 2026-04-24 17:03:46.087930

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1657b31fc815"
down_revision: str | Sequence[str] | None = "075fe2120f39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # Pre-check for orphans before adding CASCADE / SET NULL constraints
    # Check for orphaned reminder_logs.schedule_id
    res = bind.execute(
        sa.text(
            "SELECT count(*) FROM reminder_logs r "
            "LEFT JOIN medication_schedules s ON r.schedule_id = s.id "
            "WHERE r.schedule_id IS NOT NULL AND s.id IS NULL"
        )
    )
    if res.scalar() > 0:
        raise ValueError(
            "Cannot apply CASCADE: orphaned reminder_logs.schedule_id found"
        )

    # Check for orphaned reminder_logs.user_id
    res = bind.execute(
        sa.text(
            "SELECT count(*) FROM reminder_logs r "
            "LEFT JOIN users u ON r.user_id = u.id "
            "WHERE r.user_id IS NOT NULL AND u.id IS NULL"
        )
    )
    if res.scalar() > 0:
        raise ValueError("Cannot apply CASCADE: orphaned reminder_logs.user_id found")

    # Check for orphaned payments.subscription_id
    res = bind.execute(
        sa.text(
            "SELECT count(*) FROM payments p "
            "LEFT JOIN subscriptions s ON p.subscription_id = s.id "
            "WHERE p.subscription_id IS NOT NULL AND s.id IS NULL"
        )
    )
    if res.scalar() > 0:
        raise ValueError(
            "Cannot apply SET NULL: orphaned payments.subscription_id found"
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("adherence_reports_user_id_fkey"), "adherence_reports", type_="foreignkey"
    )
    op.create_foreign_key(
        "adherence_reports_user_id_fkey",
        "adherence_reports",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("medications_user_id_fkey"), "medications", type_="foreignkey"
    )
    op.create_foreign_key(
        "medications_user_id_fkey",
        "medications",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_message_logs_reminder_log_id"), "message_logs", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("message_logs_user_id_fkey"), "message_logs", type_="foreignkey"
    )
    op.create_foreign_key(
        "message_logs_user_id_fkey",
        "message_logs",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_message_logs_reminder_log_id",
        "message_logs",
        "reminder_logs",
        ["reminder_log_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("payments_subscription_id_fkey"), "payments", type_="foreignkey"
    )
    op.drop_constraint(op.f("payments_user_id_fkey"), "payments", type_="foreignkey")
    op.create_foreign_key(
        "payments_user_id_fkey",
        "payments",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "payments_subscription_id_fkey",
        "payments",
        "subscriptions",
        ["subscription_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("reminder_logs_user_id_fkey"), "reminder_logs", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("reminder_logs_schedule_id_fkey"), "reminder_logs", type_="foreignkey"
    )
    op.create_foreign_key(
        "reminder_logs_user_id_fkey",
        "reminder_logs",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "reminder_logs_schedule_id_fkey",
        "reminder_logs",
        "medication_schedules",
        ["schedule_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("subscriptions_user_id_fkey"), "subscriptions", type_="foreignkey"
    )
    op.create_foreign_key(
        "subscriptions_user_id_fkey",
        "subscriptions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "subscriptions_user_id_fkey", "subscriptions", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("subscriptions_user_id_fkey"),
        "subscriptions",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        "reminder_logs_schedule_id_fkey", "reminder_logs", type_="foreignkey"
    )
    op.drop_constraint(
        "reminder_logs_user_id_fkey", "reminder_logs", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("reminder_logs_schedule_id_fkey"),
        "reminder_logs",
        "medication_schedules",
        ["schedule_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("reminder_logs_user_id_fkey"),
        "reminder_logs",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint("payments_subscription_id_fkey", "payments", type_="foreignkey")
    op.drop_constraint("payments_user_id_fkey", "payments", type_="foreignkey")
    op.create_foreign_key(
        op.f("payments_user_id_fkey"), "payments", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("payments_subscription_id_fkey"),
        "payments",
        "subscriptions",
        ["subscription_id"],
        ["id"],
    )
    op.drop_constraint(
        "fk_message_logs_reminder_log_id", "message_logs", type_="foreignkey"
    )
    op.drop_constraint("message_logs_user_id_fkey", "message_logs", type_="foreignkey")
    op.create_foreign_key(
        op.f("message_logs_user_id_fkey"), "message_logs", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_message_logs_reminder_log_id"),
        "message_logs",
        "reminder_logs",
        ["reminder_log_id"],
        ["id"],
    )
    op.drop_constraint("medications_user_id_fkey", "medications", type_="foreignkey")
    op.create_foreign_key(
        op.f("medications_user_id_fkey"), "medications", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(
        "adherence_reports_user_id_fkey", "adherence_reports", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("adherence_reports_user_id_fkey"),
        "adherence_reports",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
