"""add_cascade_to_medication_schedules

Revision ID: 4dd76cd692ef
Revises: 1657b31fc815
Create Date: 2026-04-24 17:57:01.430668

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4dd76cd692ef"
down_revision: str | Sequence[str] | None = "1657b31fc815"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "medication_schedules_medication_id_fkey",
        "medication_schedules",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "medication_schedules_medication_id_fkey",
        "medication_schedules",
        "medications",
        ["medication_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "medication_schedules_medication_id_fkey",
        "medication_schedules",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "medication_schedules_medication_id_fkey",
        "medication_schedules",
        "medications",
        ["medication_id"],
        ["id"],
    )
    # ### end Alembic commands ###
