"""schema updates

Revision ID: d713bc16efa9
Revises: 903bbe38c426
Create Date: 2026-03-07 14:31:50.050779

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d713bc16efa9"
down_revision: str | Sequence[str] | None = "903bbe38c426"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adherence_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("report_type", sa.String(length=10), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_reminders", sa.Integer(), nullable=False),
        sa.Column("taken_count", sa.Integer(), nullable=False),
        sa.Column("missed_count", sa.Integer(), nullable=False),
        sa.Column("adherence_percentage", sa.Float(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_adherence_reports_user_id"),
        "adherence_reports",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "medications",
        sa.Column("medication_form", sa.String(length=20), server_default=sa.text("'tablet'"), nullable=False),
    )
    op.alter_column("medications", "medication_form", server_default=None)
    op.add_column("medications", sa.Column("dosage_amount", sa.Float(), nullable=True))
    op.add_column(
        "medications", sa.Column("dosage_unit", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "medications", sa.Column("frequency", sa.String(length=50), server_default=sa.text("'daily'"), nullable=False)
    )
    op.alter_column("medications", "frequency", server_default=None)
    op.add_column("medications", sa.Column("supply_days", sa.Integer(), nullable=True))
    op.add_column(
        "medications",
        sa.Column("next_refill_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "medications",
        sa.Column("treatment_end_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "medications",
        sa.Column("refill_reminder_days_before", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.alter_column("medications", "refill_reminder_days_before", server_default=None)
    op.alter_column(
        "medications", "dosage", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.add_column(
        "subscriptions",
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "trial_ends_at")
    op.alter_column(
        "medications", "dosage", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.drop_column("medications", "refill_reminder_days_before")
    op.drop_column("medications", "treatment_end_date")
    op.drop_column("medications", "next_refill_date")
    op.drop_column("medications", "supply_days")
    op.drop_column("medications", "frequency")
    op.drop_column("medications", "dosage_unit")
    op.drop_column("medications", "dosage_amount")
    op.drop_column("medications", "medication_form")
    op.drop_index(op.f("ix_adherence_reports_user_id"), table_name="adherence_reports")
    op.drop_table("adherence_reports")
    # ### end Alembic commands ###
