"""add item_type

Revision ID: fb7303f5f48e
Revises: d713bc16efa9
Create Date: 2026-03-14 09:21:02.248239

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb7303f5f48e"
down_revision: str | Sequence[str] | None = "d713bc16efa9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "medications",
        sa.Column(
            "item_type",
            sa.String(length=20),
            server_default=sa.text("'medication'"),
            nullable=False,
        ),
    )
    op.alter_column("medications", "item_type", server_default=None)
    op.alter_column(
        "medications",
        "medication_form",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "medications",
        "medication_form",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    op.drop_column("medications", "item_type")
    # ### end Alembic commands ###
